// Captures every gallery screen from the running prototype (localhost:5273).
// node capture/states.mjs shots mono 1440x900
import { chromium } from '/Users/balazs/Projects/charrette-project/charrette/apps/pitch/node_modules/@playwright/test/index.mjs'
const [out, look = 'paper', size = '1440x900'] = process.argv.slice(2)
const [w, h] = size.split('x').map(Number)
const b = await chromium.launch()
const p = await b.newPage({ viewport: { width: w, height: h }, deviceScaleFactor: 2 })
const errs = []; p.on('pageerror', e => errs.push(String(e)))
const tag = look
const shot = async (n) => { await p.waitForTimeout(450); await p.screenshot({ path: `${out}/${tag}-${n.slice(3)}.png` }) }
const home = async () => { await p.goto(`http://localhost:5273/?marks=${look}&bare`); await p.evaluate(() => document.fonts.ready); await p.waitForTimeout(500) }
await home()
await p.evaluate(() => document.querySelector('.rm-talk-scroll')?.scrollTo(0, 0)); await shot('01-talk-top')
await p.evaluate(() => document.querySelector('.rm-talk-scroll')?.scrollTo(0, 1e5)); await shot('02-talk-bottom')
await p.keyboard.press('Meta+3'); await shot('03-all')
await p.keyboard.press('Meta+2'); await shot('04-board')
await p.locator('.bd-ask', { hasText: 'Review API fallback' }).first().click(); await shot('05-board-decision-dock')
await p.keyboard.press('Escape'); await p.keyboard.press('k'); await shot('06-knowledge')
await p.keyboard.press('Escape'); await p.keyboard.press('a'); await shot('07-artifacts')
await p.keyboard.press('Escape'); await p.locator('.rm-switch').click(); await shot('08-switcher')
await p.keyboard.press('Escape')
await p.locator('.bd-card', { hasText: 'Repair token refresh' }).first().click(); await p.waitForTimeout(300)
await p.evaluate(() => document.querySelector('.tv-scroll')?.scrollTo(0, 0)); await shot('09-task-top')
await p.keyboard.press('o'); await shot('10-task-outputs')
await p.keyboard.press('c'); await p.keyboard.press('g'); await shot('11-task-graph')
await p.keyboard.press('Escape'); await p.keyboard.press('d'); await shot('12-task-diff')
await p.keyboard.press('Escape'); await p.keyboard.press('Escape')
for (const [t, n] of [['Find a shape for webhook', '13-task-session'], ['Why do refunds fail fast', '14-task-question']]) {
  await p.locator('.bd-card, .bd-row', { hasText: t }).first().click(); await p.waitForTimeout(300)
  await p.evaluate(() => document.querySelector('.tv-scroll')?.scrollTo(0, 0)); await shot(n)
  await p.keyboard.press('Escape')
}
await p.locator('.bd-row', { hasText: 'Extract rate-limit' }).first().click(); await shot('15-next')
await p.goto(`http://localhost:5273/?marks=${look}&bare&task=418&state=settled`); await p.evaluate(() => document.fonts.ready); await shot('16-task-merged')
await p.goto(`http://localhost:5273/?marks=${look}&bare&task=418&state=ready`); await p.evaluate(() => document.fonts.ready); await shot('17-task-ready')
await p.goto(`http://localhost:5273/?marks=${look}&bare&task=431`); await p.evaluate(() => document.fonts.ready); await shot('50-task-431')
await p.goto(`http://localhost:5273/?marks=${look}&bare&task=418&state=needs`); await p.evaluate(() => document.fonts.ready); await shot('51-task-held')
await p.goto(`http://localhost:5273/?marks=${look}&bare`); await p.evaluate(() => document.fonts.ready); await p.keyboard.press('Meta+2'); await p.locator('.bd-review').first().click(); await shot('18-board-review')
await p.keyboard.press('Escape'); await p.keyboard.press('Shift+K'); await shot('19-knowledge-room')
await home()
await p.locator('.cz textarea').first().click(); await p.keyboard.type('Pick up the refund retry work next.'); await p.keyboard.press('Shift+Enter'); await p.keyboard.type('Keep it off main until I have looked.')
await p.locator('.cz .mp-b').first().click(); await shot('20-model-picker')
await p.locator('.mp-all').click(); await shot('21-model-browser')
await p.keyboard.press('Escape'); await p.locator('.cz-ctx').first().hover(); await shot('22-context')
await p.keyboard.press('Meta+3'); await p.locator('.rm-menu-b').click(); await shot('23-project-menu')
await p.goto(`http://localhost:5273/?bare#chat`); await p.evaluate(() => document.fonts.ready)
const spec = async (id) => { await p.evaluate((id) => document.querySelector('#s-' + id).scrollIntoView({ block: 'start' }), id); await p.waitForTimeout(200) }
for (const [id, n] of [['you', '24-chat-start'], ['reply', '25-chat-tools'], ['web', '26-chat-outside'], ['perm', '27-chat-waiting'], ['code', '28-chat-handback'], ['compact', '29-chat-live'], ['thinking', '30-chat-edges']]) {
  await spec(id); await shot(n)
}
await p.click('.cs-seg-b:has-text("Dark")'); await spec('run'); await shot('31-chat-dark-terminal'); await p.click('.cs-seg-b:has-text("Paper")')
await spec('file'); await p.click('.cs-art-prev'); await p.waitForTimeout(400); await shot('32-chat-panel'); await p.keyboard.press('Escape')
await spec('step'); await shot('35-chat-steps')
await spec('parallel'); await shot('36-chat-review')
await spec('graph'); await p.click('#s-graph .cs-step-more'); await shot('37-chat-graph')
await spec('steer'); await p.click('#s-steer .cs-step-go:has-text("Thread")'); await p.waitForTimeout(300)
await p.click('.cs-sp-compose textarea'); await p.keyboard.type('Also look at how refunds are logged when refused.'); await p.keyboard.press('Enter'); await shot('38-chat-step-thread'); await p.keyboard.press('Escape')
await spec('empty'); await p.click('.cs-lead-b'); await shot('39-chat-lead'); await p.keyboard.press('Escape')
await spec('perms'); await shot('40-chat-permissions')
await spec('allowed'); await shot('41-chat-allowed')
await spec('rules'); await shot('42-chat-rules')
await spec('settled'); await p.click('#s-settled .cs-step-more'); await shot('43-chat-review-settled')
await spec('launch'); await shot('44-chat-launch')
await spec('started'); await shot('46-chat-task-running')
await spec('history'); await shot('47-chat-task-history')
await spec('out'); await shot('48-chat-plan-out')
await spec('paused'); await shot('49-chat-task-paused')
await spec('shots'); await shot('45-chat-images')
await p.click('.cs-seg-b:has-text("Conversation")'); await p.waitForTimeout(300); await shot('33-chat-flow')
await p.evaluate(() => { const s = document.querySelector('.cs-scroll'); s.scrollTop = s.scrollHeight }); await p.waitForTimeout(300); await shot('34-chat-flow-live')
console.log(errs)
await b.close()
